name: Deploy

on:
  push:
    branches: [master]
  schedule:
    - cron: '59 23 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Build & Test & Run
        run: |
          wget -O all.xml.gz 'https://www.czechpoint.cz/spravadat/ovm/datafile.do?format=xml&service=seznamovm'
          gunzip all.xml.gz
          yarn install
          yarn test
          RUIAN_API_KEY=${{ secrets.RUIAN_API_KEY }} yarn start
      - name: Prepare for upload
        run: |
          mkdir dist
          mv obce.json dist
      - name: Upload artifacts
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: data-cesko-digital
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          AWS_REGION: "eu-central-1"
          SOURCE_DIR: "dist"
          DEST_DIR: "obce/1"
